2020-04-23 10:43:30,654 ERROR: Exception on /user/susan [GET] [in d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Programowanie\Flask_microblog\app\routes.py", line 100, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
AttributeError: 'function' object has no attribute 'posts'
2020-04-23 10:43:47,223 ERROR: Exception on /user/test [GET] [in d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Programowanie\Flask_microblog\app\routes.py", line 100, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
AttributeError: 'function' object has no attribute 'posts'
2020-04-23 10:43:51,708 ERROR: Exception on /user/susan [GET] [in d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Programowanie\Flask_microblog\app\routes.py", line 100, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
AttributeError: 'function' object has no attribute 'posts'
2020-04-23 10:43:53,028 ERROR: Exception on /user/susan [GET] [in d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Programowanie\Flask_microblog\app\routes.py", line 100, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
AttributeError: 'function' object has no attribute 'posts'
2020-04-23 10:43:54,393 ERROR: Exception on /user/susan [GET] [in d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Programowanie\Flask_microblog\app\routes.py", line 100, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
AttributeError: 'function' object has no attribute 'posts'
2020-04-23 10:43:55,344 ERROR: Exception on /user/susan [GET] [in d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\programowanie\flask_microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Programowanie\Flask_microblog\app\routes.py", line 100, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
AttributeError: 'function' object has no attribute 'posts'
